package com.ndu.mobile.daisy.providers.librivox;

public class Constants
{
	public static final String[] Categories = {
		"Adventure",
		"Advice",
		"Ancient Texts",
		"Animals",
		"Art",
		"Biography",
		"Children",
		"Classics (antiquity)",
		"Comedy",
		"Cookery",
		"Economics/Political Economy",
		"Epistolary fiction",
		"Erotica",
		"Essay/Short nonfiction",
		"Fairy tales",
		"Fantasy",
		"Fiction",
		"Historical Fiction",
		"History",
		"Holiday",
		"Horror/Ghost stories",
		"Humor",
		"Instruction",
		"Languages",
		"Literature",
		"Memoirs",
		"Music",
		"Mystery",
		"Myths/Legends",
		"Nature",
		"Philosophy",
		"Play",
		"Poetry",
		"Politics",
		"Psychology",
		"Romance",
		"Religion",
		"Satire",
		"Science",
		"Science fiction",
		"Sea stories",
		"Short stories",
		"Spy stories",
		"Teen/Young adult",
		"Tragedy",
		"Travel",
		"War stories",
		"Westerns",
	};
}
